language: python
dist: precise
sudo: false
python:
  - "3.6"
  - "3.5"
  - "2.7"

addons:
  postgresql: "9.4"

install:
  - "pip install coveralls"
  - "pip install -r requirements/test.txt"

before_script:
  - psql -c 'create database osmcha;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d osmcha
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d osmcha

script:
- coverage run manage.py test --settings=config.settings.tests

after_success:
  - coveralls

notifications:
  email: false
